In [1]:
import pandas as pd
df=pd.read_csv("cleaned_df.csv")
df

,Unnamed: 0,Country,Zone,Region,Territory,Product Category,Qty,MRP,% Discount,Selling Price,Sales,Order Priority,Delivery Mode,Processing Time (days),Financial Year,Financial Month
0,0,India,Western,Gujarat,Vadodara,Air Coolers,43.0,9000,0.08,8280.0,356040.0,Low,Road,3,2012,4
1,1,India,Northern,Delhi,New Delhi,Water Dispensers,55.0,4000,0.01,3960.0,217800.0,High,Air,5,2012,4
2,2,India,Eastern,Bihar,Gaya,Air Conditioners,42.0,74000,0.12,65120.0,2735040.0,High,Air,4,2012,4
3,3,India,North-Eastern,Assam,Guwahati,Air Conditioners,55.0,57000,0.12,50160.0,2758800.0,Medium,Rail,2,2012,4
4,4,India,Northern,Rajasthan,Udaipur,Air Conditioners,36.0,22000,0.19,17820.0,641520.0,High,Air,0,2012,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9854,9854,Sri Lanka,Uva Province,Uva Province,Badulla,Refrigerators,49.0,19000,0.06,17860.0,875140.0,Low,Road,5,2021,2
9855,9855,Sri Lanka,Sabaragamuwa,Sabaragamuwa,Ratnapura,Air Coolers,69.0,11000,0.07,10230.0,705870.0,Express,Air,1,2021,2
9856,9856,Sri Lanka,Western Province,Western Province,Colombo,Refrigerators,33.0,39000,0.13,33930.0,1119690.0,Medium,Rail,0,2021,3
9857,9857,Sri Lanka,Eastern Province,Eastern Province,Trincomalee,Refrigerators,82.0,19000,0.14,16340.0,1339880.0,High,Air,4,2021,3
9858,9858,Sri Lanka,North Western Province,North Western Province,Kurunegala,Water Dispensers,43.0,8000,0.05,7600.0,326800.0,Low,Road,1,2021,3